spring:
  jwt:
    secret: ${KEY}

  security:
    redirectURL: ${LOGIN_REDIRECT}
    githubToken: ${GITHUB_TOKEN}
    oauth2:
      client:
        registration:
          github:
            client-name: Github
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_KEY}
            redirect-uri: ${GITHUB_CALLBACK}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

  datasource:
    url: jdbc:mysql://${DB}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true