spring:
  jwt:
    secret: ${KEY}

  security:
    redirectURL: http://localhost:3000
    oauth2:
      client:
        registration:
          github:
            client-name: Github
            client-id: ${Github_ID}
            client-secret: ${Github_KEY}

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/test
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
