ALTER TABLE comment
    MODIFY review VARCHAR(500) NOT NULL;

ALTER TABLE comment ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comment ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;